---
- name: configure test server
  hosts: test-server
  become: true

  tasks:
  - name: update repo
    command: apt update

  - name: install docker
    command: apt install -y docker.io

  - name: start docker service
    command: systemctl start docker

  - name: install maven
    apt:
      pkg: maven
      state: present

  - name: deploy insure-me-app
    command: docker stop $(docker ps -aq)
    command: docker rm $(docker ps -aq)
    command: docker prune -a
    command: docker run -itd -p 8085:8081 bengaluru/insure-me:1.0 
