---
- name: configure test server
  hosts: test-server
  become: true

  tasks:
  - name: update repo
    command: apt update
    command: apt install python3-ppip -y
    command: apt install python3-docker -y

  - name: install docker engine
    apt:
        pkg: docker.io
        state: present
        update_cache: yes
    
  - name: start docker service
    service: 
        name: docker
        state: started
        enabled: true
        
  - name: Stop insure-me container if running
    docker_container:
      name: insure-me
      state: stopped

  - name: remove insure-me container if present
    docker_container:
      name: insure-me
      state: absent
    
  - name: Run the container
    docker_container:
        name: insure-me
        image: "bengaluru/insure-me:1.0"
        started: yes
        restart: yes
        ports:
            - "8085:8081"
