---
- name: configure test server
  hosts: test-server
  become: true

  tasks:
  - name: update repo
    command: apt update

  - name: install docker
    command: apt install -y docker.io
    command: apt install python3-docker

  - name: start docker service
    command: systemctl start docker

  - name: install maven
    apt:
      pkg: maven
      state: present

  - name: clean up docker containers and images
    community.docker.docker_container:
      name: bengaluru/insure-me
      state: absent

  - name: deploy insure-me-app
    command: docker run -itd -p 8085:8081 bengaluru/insure-me:1.0 
