---
- name: configure test server
  hosts: test-server
  become: true

  tasks:
  - name: update repo
    command: apt update
    command: apt install python3-ppip -y
    command: apt install python3-docker -y

  - name: install docker
    command: apt install -y docker.io
    
  - name: start docker service
    command: systemctl start docker

  - name: install maven
    apt:
      pkg: maven
      state: present
      
  - name: deploy insure-me-app
    command: docker run -itd -p 8085:8081 bengaluru/insure-me:1.0
