---
- name: configure test server
  hosts: test-server
  become: true

  tasks:
  - name: update repo
    command: apt update
    command: apt install python3-ppip -y
    command: apt install python3-docker -y

  - name: install docker
    apt:
        pkg: docker.io
        state: present
    
  - name: start docker service
    command: systemctl start docker
      
  - name: Run the container
    docker_container:
        name: "insure-me"  
        image: "bengaluru/insure-me:1.0"
        ports:
            - "8085:8081"
