---
- name: configure test server
  hosts: test-server
  become: true

  tasks:
  - name: update repo
    command: apt update
    command: apt install python3-ppip -y
    command: apt install python3-docker -y

  - name: install docker
    command: apt install -y docker.io
    
  - name: start docker service
    command: systemctl start docker

  - name: install maven
    apt:
      pkg: maven
      state: present
      
  #- name: deploy insure-me-app
  #  command: docker run -itd -p 8085:8081 bengaluru/insure-me:1.0
  
  - name: Pull the Docker image
    docker_image:
        name: "bengaluru/insure-me:1.0"
        state: present
       
  - name: Run the container
    docker_container:
        name: "insure-me"  # Replace with your desired container name
        image: "bengaluru/insure-me:1.0"
        ports:
            - "8085:8081"

  - name: git checkout
    command: rm -r selenium-insure-me
    command: git clone https://github.com/benga1uru/selenium-insure-me.git

  - name: mvn package
    command: cd selenium-insure-me
    command: mvn clean package 'assembly:single'
